language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.2 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=nightly WP_MULTISITE=1
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.2 WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=1
  allow_failures:
    - php: 5.6
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=nightly WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=1
  fast_finish: true

